services:
  bot:
    image: ${DOCKER_USERNAME}/${REPOSITORY_NAME}
    container_name: bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - ACCESS_PASSWORD=${ACCESS_PASSWORD}
    restart: always