name: CI/CD

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest

  prepare-environment:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Stop and remove containers, networks
        run: docker compose down
        continue-on-error: true
      - name: Remove unused data
        run: docker system prune -a -f
        continue-on-error: true

  deploy:
    runs-on: self-hosted
    needs: prepare-environment
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: docker compose
        env:
          DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
          REPOSITORY_NAME: ${{ github.event.repository.name }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: docker compose up -d

